# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mohd Tajul Asri B. Rosli
title: Senior Technical Developer
email: mtajulasri@gmail.com
website: tajulasri.github.io
phone: +60 145387564 

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
linkedin_username: tajul-asri-204b4492
github_username:  tajulasri
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced software developer with a proven track record of designing, developing, and optimizing web-based and mobile applications. 
  Currently serving as Senior Technical Developer at Supreme EBanq Fintech, leading mobile development and microservices architecture.
  
  Proficient in PHP, JavaScript, Go, Python, and Dart with extensive experience in fintech solutions, email marketing platforms, 
  and high-performance web applications serving millions of users.
  
  Specialized in mobile development (iOS/Android), system architecture design, and scalable deployment solutions.
content:
  - title: Technical Skills
    layout: list
    content:
      - layout: left
        sub_title: Programming Languages
        caption: PHP • JavaScript • Go • Python • Dart
        description: |
          Proficient in multiple programming languages with extensive experience in building scalable applications and optimization.
    
      - layout: left
        sub_title: Databases & Storage  
        caption: MySQL • PostgreSQL • MongoDB • Redis
        description: |
          Experience with both SQL and NoSQL databases, data modeling, query optimization, and caching strategies.

      - layout: left
        sub_title: Mobile Development
        caption: Flutter SDK • iOS • Android • Cross-platform Development
        description: |
          Specialized in mobile application development using Flutter SDK for both iOS and Android platforms, including e-wallet and POS systems.

      - layout: left
        sub_title: DevOps & Monitoring
        caption: Docker • Kubernetes • Git • Linux • Unit Testing • Grafana
        description: |
          Expertise in containerization, deployment pipelines, system monitoring, and maintaining high-quality code through testing practices.

  - title: Featured Projects
    layout: list
    content:
      - layout: top-middle
        title: Mobile E-Wallet Application (iOS/Android)
        sub_title: Team Lead & Mobile Development
        caption: Flutter • iOS • Android • Fintech • Payment Systems
        description: |
          Leading the development of a mobile e-wallet application for Supreme EBanq Fintech. Responsible for system architecture design, 
          development pipeline implementation, and deployment planning. Currently involved in R&D for Android Mobile POS using payment terminals.

      - layout: top-middle
        title: Go.my URL Shortener Platform
        sub_title: High-Performance Web Application
        caption: Go • PHP • High-Traffic Systems • Optimization
        description: |
          Designed, developed and optimized URL shortener service serving millions of URL shortening requests monthly. 
          Built scalable architecture to handle high-traffic loads with optimized performance and reliability.

      - layout: top-middle
        title: Email Marketing & SMS Platform
        sub_title: Full-Stack Development & Optimization
        caption: PHP • JavaScript • MTA • API Integration • Frontend Optimization
        description: |
          Designed and optimized SMS sending services, email marketing web applications, and Mail Transfer Agent (MTA) codebase. 
          Improved system speed, reliability, and user experience across marketing platforms and API integrations.

  - title: Professional Experience
    layout: list
    content:
      - layout: left
        title: Supreme EBanq Fintech (SARAWAK) Bhd.
        sub_title: Senior Technical Developer (Mobile, Microservices)
        caption: 2024 - Current
        quote: >
          Leading mobile development and system architecture for fintech solutions
        description: |
          • **Team Leadership:** Leading Mobile (iOS, Android) e-wallet project team including planning and development phases
          • **System Architecture:** Designing and implementing system architecture, deployment pipelines and infrastructure planning
          • **Research & Development:** Actively involved in R&D for Android Mobile POS using payment terminal technology
          • **Fintech Expertise:** Specialized in financial technology solutions and payment systems integration

      - layout: left
        title: Web Impian Sdn Bhd.
        sub_title: Senior Programmer
        caption: 2022 - 2024
        quote: >
          High-performance systems and marketing platform optimization
        description: |
          • **SMS Services:** Designed, developed and optimized SMS sending services improving speed and reliability
          • **Frontend Optimization:** Enhanced marketing SMS web portal frontend for better user experience
          • **Email Systems:** Designed and optimized MTA (Mail Transfer Agent) codebase powering email marketing software and API integrations
          • **High-Traffic Applications:** Developed and optimized Go.my URL shortener serving millions of monthly requests
          • **Deployment:** Actively involved in product deployment and infrastructure management

      - layout: left
        title: Codexpert Resources
        sub_title: Software Developer
        caption: 2018 - 2022
        quote: >
          Full-stack development and mobile application expertise
        description: |
          • **Web Applications:** Designed, developed and optimized web-based applications based on client requirements
          • **Mobile Development:** Specialized in Flutter SDK mobile application development
          • **Deployment:** Participated in application deployment and maintenance processes
          • **Client Solutions:** Delivered custom software solutions meeting specific business requirements

      - layout: left
        title: Nazrol Tech Sdn Bhd.
        sub_title: Developer
        caption: 2016 - 2017
        quote: >
          Frontend specialization and web application development
        description: |
          • **Web Development:** Designed, developed and optimized web-based applications for client requirements
          • **Frontend Expertise:** Specialized in AngularJS frontend application development
          • **Deployment:** Involved in application deployment and production maintenance


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Polytechnic Sultan Mizan Zainal Abidin
        caption: 2010 - 2013
        sub_title: Dip Mechanical Engineering (Plastic)
        quote: >
          The part of Polytechnic missions is a to empower communities through lifelong learning.

        description: | # this will include new lines to allow paragraphs
          During my time in Polytechnic i learnt how to think systematically according to engineering practice and working in team to accomplished tight dateline assignments. Eventhough with tight schedule i love to balance my student life with outdoor sports.

  - title: Beyond Technology
    layout: text
    content: |
      When I'm not coding, I enjoy pursuing activities that help maintain work-life balance and continuous learning:
      
      **Outdoor Activities:** Fishing and cycling help me stay active and provide mental clarity for problem-solving
      
      **Continuous Learning:** Reading technical blogs, industry publications, and contributing to open-source projects
      
      **Professional Development:** Attending tech meetups, conferences, and mentoring aspiring developers in the community 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
