# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Mohd Tajul Asri
title: Fullstack Developer
email: mtajulasri@gmail.com
website: tajulasri.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
linkedin_username: tajul-asri-204b4492
github_username:  tajulasri
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 A software developer with hands-on experience in all processes in software development life cycle starting from designing to implementing next is deploying and maintaining the products by collecting relevant metrics for further improvisation.
content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Programming Language
        caption: PHP, Javascript, Python, NodeJS, Dart
        # link: github.com/sproogen
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
         Common and fluent programming languages in daily job routine.
    
      - layout: left
        sub_title: Frameworks
        caption: Laravel, ExpressJS, NestJS, Flutter, Angular, Vue
        # link: github.com/sproogen
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
         Common and fluent programming frameworks in daily job routine.

      - layout: left
        sub_title: Others
        caption: API Documentation, Version Control(GIT), Unit Testing, Linux, Docker.
        # link: github.com/sproogen
        # link_text: Project Website
        description: | # this will include new lines to allow paragraphs
         Others skills to complete software engineering working flow in daily job routine.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Geliga World Sdn Bhd
        #link: https://www.shareinvestor.com/
        # link_text: boringcompany.com
        sub_title: Backend Developer
        caption: July 2015 - Jun 2016
        quote: >
          Solving problems related with backend issues and getting involved in developing new products.
        description: | # this will include new lines to allow paragraphs
            Product base never be easy even in software engineering, solving a puzzle according to product's owner is quite challenging while maintaining the performance and coding standard but everything is quite smooth via teamwork.

      - layout: left
        title: Nazrol Tech Sdn Bhd
        #link: https://www.shareinvestor.com/
        # link_text: boringcompany.com
        sub_title: Backend Developer
        caption: Jun 2016 - July 2017
        quote: >
          Getting serious about backend development
        description: | # this will include new lines to allow paragraphs
           Working with large number of developers in a single team to accomplished sprint using agile methodology, as backend developer in the team im focusing the REST api development
           to deliver most presentable and reliable REST api to frontend team to meet high standard UX design guideline.

      - layout: left
        title: Codexpert Resources
        #link: https://www.shareinvestor.com/
        # link_text: boringcompany.com
        sub_title: Sr Software Developer
        caption: January 2018 - Present
        quote: >
          Lead the team, designing architecture is part of my duty here and of course coding contribution.
          
        description: | # this will include new lines to allow paragraphs
          At this phase, the most important skills is reading and researching and refactoring current codebase according to standard guideline, also getting involved in designing architecture according to problem statement 
          for an example microservices pattern such as event sourcing pattern.

          Getting involed in mobile app development using Flutter framework, designing and choose practicle state management pattern in mobile development is quite challenging.

          Code review and unit testing.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Polytechnic Sultan Mizan Zainal Abidin
        caption: 2010 - 2013
        sub_title: Dip Mechanical Engineering (Plastic)
        quote: >
          The part of Polytechnic missions is a to empower communities through lifelong learning.

        description: | # this will include new lines to allow paragraphs
          During my time in Polytechnic i learnt how to think systematically according to engineering practice and working in team to accomplished tight dateline assignments. Eventhough with tight schedule i love to balance my student life with outdoor sports.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in software engineering some of my other interests and hobbies are:
      - Fishing
      - Cycling
      - Reading 

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
